[global]
server_name = "theorem-nova-merry-acute.trycloudflare.com"
database_path = "/var/lib/tuwunel"
address = "0.0.0.0"
port = 8448
allow_registration = true
yes_i_am_very_very_sure_i_want_an_open_registration_server_prone_to_abuse = true

[global.well_known]
server = "theorem-nova-merry-acute.trycloudflare.com:443"
client = "https://theorem-nova-merry-acute.trycloudflare.com"